# Generated by Django 5.0.2 on 2024-03-20 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend_web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='headshot',
            field=models.ImageField(default='img/headshots/default.png', null=True, upload_to='img/headshots/'),
        ),
    ]
